from __future__ import annotations

import streamlit as st

from ui.graph_helpers import get_state, safe_state, persist, update_graph_state
from ui.state_store import update_store


_CLEAR_BY_STAGE = {
    "eda": [
        "hitl_eda_approved",
        "hitl_leakage_approved",
        "hitl_features_approved",
        "hitl_split_approved",
        "hitl_model_selection_approved",
        "hitl_models_approved",
        "hitl_loop_approved",
        "hitl_final_accepted",
        "hitl_ensemble_approved",
        "leakage_report",
        "feature_proposals",
        "selected_features",
        "df_engineered_parquet_b64",
        "feature_analysis",
        "split_strategy",
        "split_rationale",
        "split_warnings",
        "split_analysis",
        "model_candidates",
        "model_recommendation",
        "tuning_results",
        "best_model_key",
        "best_params",
        "best_cv_score",
        "best_nn_config",
        "all_model_params",
        "model_analysis",
        "eval_metrics",
        "shap_importance",
        "eval_report",
        "eval_analysis",
        "calibration_metrics",
        "metric_ci",
        "top_shap_features",
        "ensemble_report",
        "orchestrator_decision",
        "orchestrator_analysis",
        "loop_verdict",
        "loop_reasoning",
        "loop_suggestion",
        "loop_feature_strategy",
        "loop_model_strategy",
        "_forced_model_candidates",
        "_best_model_b64",
        "_X_train_t_b64",
        "_X_test_t_b64",
        "_y_train_b64",
        "_y_test_b64",
        "_X_cal_t_b64",
        "_y_cal_b64",
        "_feature_names",
        "_preprocessor_b64",
        "_label_encoder_b64",
        "_baseline_score",
        "_custom_thresholds",
        "eda_plots",
        "user_selected_models",
        "user_added_models",
        "llm_model_candidates",
    ],
    "leakage": [
        "hitl_leakage_approved",
        "hitl_features_approved",
        "hitl_split_approved",
        "hitl_model_selection_approved",
        "hitl_models_approved",
        "hitl_loop_approved",
        "hitl_final_accepted",
        "hitl_ensemble_approved",
        "feature_proposals",
        "selected_features",
        "df_engineered_parquet_b64",
        "feature_analysis",
        "split_strategy",
        "split_rationale",
        "split_warnings",
        "split_analysis",
        "model_candidates",
        "model_recommendation",
        "tuning_results",
        "best_model_key",
        "best_params",
        "best_cv_score",
        "best_nn_config",
        "all_model_params",
        "model_analysis",
        "eval_metrics",
        "shap_importance",
        "eval_report",
        "eval_analysis",
        "calibration_metrics",
        "metric_ci",
        "top_shap_features",
        "ensemble_report",
        "orchestrator_decision",
        "orchestrator_analysis",
        "loop_verdict",
        "loop_reasoning",
        "loop_suggestion",
        "loop_feature_strategy",
        "loop_model_strategy",
        "_forced_model_candidates",
        "_best_model_b64",
        "_X_train_t_b64",
        "_X_test_t_b64",
        "_y_train_b64",
        "_y_test_b64",
        "_X_cal_t_b64",
        "_y_cal_b64",
        "_feature_names",
        "_preprocessor_b64",
        "_label_encoder_b64",
        "_baseline_score",
        "_custom_thresholds",
        "eda_plots",
        "user_selected_models",
        "user_added_models",
        "llm_model_candidates",
    ],
    "features": [
        "hitl_features_approved",
        "hitl_split_approved",
        "hitl_model_selection_approved",
        "hitl_models_approved",
        "hitl_loop_approved",
        "hitl_final_accepted",
        "hitl_ensemble_approved",
        "selected_features",
        "df_engineered_parquet_b64",
        "split_strategy",
        "split_rationale",
        "split_warnings",
        "split_analysis",
        "model_candidates",
        "model_recommendation",
        "tuning_results",
        "best_model_key",
        "best_params",
        "best_cv_score",
        "best_nn_config",
        "all_model_params",
        "model_analysis",
        "eval_metrics",
        "shap_importance",
        "eval_report",
        "eval_analysis",
        "calibration_metrics",
        "metric_ci",
        "top_shap_features",
        "ensemble_report",
        "orchestrator_decision",
        "orchestrator_analysis",
        "loop_verdict",
        "loop_reasoning",
        "loop_suggestion",
        "loop_feature_strategy",
        "loop_model_strategy",
        "_forced_model_candidates",
        "_best_model_b64",
        "_X_train_t_b64",
        "_X_test_t_b64",
        "_y_train_b64",
        "_y_test_b64",
        "_X_cal_t_b64",
        "_y_cal_b64",
        "_feature_names",
        "_preprocessor_b64",
        "_label_encoder_b64",
        "_baseline_score",
        "_custom_thresholds",
        "eda_plots",
        "user_selected_models",
        "user_added_models",
        "llm_model_candidates",
    ],
    "split": [
        "hitl_split_approved",
        "hitl_model_selection_approved",
        "hitl_models_approved",
        "hitl_loop_approved",
        "hitl_final_accepted",
        "hitl_ensemble_approved",
        "model_candidates",
        "model_recommendation",
        "tuning_results",
        "best_model_key",
        "best_params",
        "best_cv_score",
        "best_nn_config",
        "all_model_params",
        "model_analysis",
        "eval_metrics",
        "shap_importance",
        "eval_report",
        "eval_analysis",
        "calibration_metrics",
        "metric_ci",
        "top_shap_features",
        "ensemble_report",
        "orchestrator_decision",
        "orchestrator_analysis",
        "loop_verdict",
        "loop_reasoning",
        "loop_suggestion",
        "loop_feature_strategy",
        "loop_model_strategy",
        "_forced_model_candidates",
        "_best_model_b64",
        "_baseline_score",
        "_custom_thresholds",
        "user_selected_models",
        "user_added_models",
        "llm_model_candidates",
    ],
    "model_selection": [
        "hitl_model_selection_approved",
        "hitl_models_approved",
        "hitl_loop_approved",
        "hitl_final_accepted",
        "hitl_ensemble_approved",
        "tuning_results",
        "best_model_key",
        "best_params",
        "best_cv_score",
        "best_nn_config",
        "all_model_params",
        "model_analysis",
        "eval_metrics",
        "shap_importance",
        "eval_report",
        "eval_analysis",
        "calibration_metrics",
        "metric_ci",
        "top_shap_features",
        "ensemble_report",
        "orchestrator_decision",
        "orchestrator_analysis",
        "loop_verdict",
        "loop_reasoning",
        "loop_suggestion",
        "loop_feature_strategy",
        "loop_model_strategy",
        "_best_model_b64",
    ],
    "models": [
        "hitl_models_approved",
        "hitl_loop_approved",
        "hitl_final_accepted",
        "hitl_ensemble_approved",
        "eval_metrics",
        "shap_importance",
        "eval_report",
        "eval_analysis",
        "calibration_metrics",
        "metric_ci",
        "top_shap_features",
        "ensemble_report",
        "orchestrator_decision",
        "orchestrator_analysis",
        "loop_verdict",
        "loop_reasoning",
        "loop_suggestion",
        "loop_feature_strategy",
        "loop_model_strategy",
    ],
}

_RESET_DEFAULTS = {
    "feature_proposals": [],
    "selected_features": [],
    "split_warnings": [],
    "model_candidates": [],
    "tuning_results": [],
    "shap_importance": [],
    "top_shap_features": [],
    "user_selected_models": [],
    "user_added_models": [],
    "llm_model_candidates": [],
    "_forced_model_candidates": [],
    "agent_messages": [],
}


def _default_reset_value(key: str):
    value = _RESET_DEFAULTS.get(key)
    if isinstance(value, list):
        return list(value)
    if isinstance(value, dict):
        return dict(value)
    return value


def reopen_workflow_stage(stage: str, *, tid: str, phase: str, note: str | None = None) -> None:
    current = dict(get_state(tid) or st.session_state.get("pipeline_state", {}) or {})
    patch = {k: _default_reset_value(k) for k in _CLEAR_BY_STAGE.get(stage, [])}

    if stage == "eda":
        patch["hitl_eda_approved"] = False
    if stage == "leakage":
        patch["hitl_leakage_approved"] = False
    if stage == "features":
        patch["hitl_features_approved"] = False
    if stage == "split":
        patch["hitl_split_approved"] = False
    if stage == "model_selection":
        patch["hitl_model_selection_approved"] = False
    if stage == "models":
        patch["hitl_models_approved"] = False

    patch["agent_messages"] = list(current.get("agent_messages", []))
    if note:
        patch["agent_messages"].append(note)

    update_graph_state(patch, tid)
    new_state = safe_state({**current, **patch})
    st.session_state.pipeline_state = new_state
    st.session_state.phase = phase
    update_store(pipeline_state=new_state, phase=phase)
    persist(tid, {**current, **patch}, phase=phase)
    st.rerun()
